- hosts: win
  tasks:

  - name: Create ansible directory
    win_file:
      path: C:\ansible
      state: directory

  - name: Download Erlang installer
    win_get_url:
      url: "https://github.com/erlang/otp/releases/download/OTP-27.0/otp_win64_27.0.exe"
      dest: "C:\ansible\otp_win64_27.0.exe"

  - name: Download RabbitMQ installer
    win_get_url:
      url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.2/rabbitmq-server-3.13.2.exe"
      dest: "C:\ansible\rabbitmq-server-3.13.2.exe"

  - name: Open port 15672 in Windows Firewall
    win_firewall_rule:
      name: "Open Port 15672"
      localport: "15672"
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
      profile: private

  - name: Check if the Erlang is already installed
    win_stat:
      path: C:\ansible\erlang_installed.marker
    register: erlang_installed

  - name: Execute Erlang installer
    win_shell: Start-Process "C:\ansible\rabbitmq-server-3.13.2.exe" -ArgumentList "/S" -Wait -NoNewWindow
    when: not erlang_installed.stat.exists
    register: erlang_install_result


  - name: Create a marker file if installation is successful
    win_file:
      path: C:\ansible\erlang_installed.marker
      state: touch
    when:
      - erlang_install_result is defined
      - "'rc' in erlang_install_result"
      - erlang_install_result.rc == 0


  - name: Check if rabbitmq is already installed
    win_stat:
      path: C:\ansible\rabbitmq_installed.marker
    register: rabbitmq_installed

  - name: Execute rabbitmq installer
    win_shell: |
      $proc = Start-Process "C:\ansible\rabbitmq-server-3.13.2.exe" -ArgumentList "/S" -Wait:$false -Passthru
      Wait-Process -Id $proc.Id
    when: not rabbitmq_installed.stat.exists
    register: rabbitmq_install_result


  - name: Create a marker file if installation is successful
    win_file:
      path: C:\ansible\rabbitmq_installed.marker
      state: touch
    when:
      - rabbitmq_install_result is defined
      - "'rc' in rabbitmq_install_result"
      - rabbitmq_install_result.rc == 0
